#!/bin/bash

currentWindow () {
  id=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
  name=$(xprop -id $id | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)
  echo "$name"
}

i3status |
  while read line
  do echo "$(currentWindow)   $line"
  done
